### ISSUE TITLE
Audiotrace in Desmodder video creator

### ISSUE THREAD

**Issue by RannyBergamotte** [DesModder/DesModder#119]
Video plugin feature request:
Allow a desmodder video to be created that uses the audiotrace time instead of slider/simulation, and records the audio from the audiotrace or the custom sound javascript.

**Comment by jared-hughes** [comment]
Closing because recording audio in Desmodder would really only be useful to you (and a few other people perhaps), and only slightly useful at that because audio is already real-time.

If you want the small audiotrace bug to get fixed properly, the best way is to submit a request at http://support.desmos.com/
