### ISSUE TITLE
Add scientific notation (and more?)

### ISSUE THREAD

**Issue by TJCgames** [DesModder/DesModder#189]
Please give desmodder support for knuth's up-arrow, scientific, and double exponential notation. (2↑↑4, 1e5, and ee4, respectively)

**Comment by TJCgames** [comment]
I mean, scientific and double exponential are easily recreatable, as x*10^y and 10^10^x, respectively, but i think it would be easier if you could just type them and be done with it

**Comment by jared-hughes** [comment]
1. Probably won't implement Knuth's up-arrow notation because it's so rarely used, and Desmos only supports floats with magnitude less than 2^1024.
2. Scientific notation sounds good. Might implement it using capital `E` like `1E5` to avoid confusion with `e`.
3. Do you have any reference for double-exponential notation? I've never seen it used before

**Comment by TJCgames** [comment]
> 3. Do you have any reference for double-exponential notation? I've never seen it used before

Its used for really big numbers in exponential idle. Basically, EEx = 10^10^x. Don't worry, 1E1000 is only EE4

**Comment by jared-hughes** [comment]
Scientific notation has been implemented in #373.
