### ISSUE TITLE
Add "hide" button for sliders, and replace left-click with shift-left-click

### ISSUE THREAD

**Issue by naxmivv** [DesModder/DesModder#256]
since people are already used to lclick to read an error message, rclick should instead be assigned to hiding the error message while lclick retains its original functionality.

**Comment by jared-hughes** [comment]
Some time in the past few days, Desmos changed how they set tooltips as sticky, so DesModder no longer disables that for error messages.

To some degree, I like the new behavior because it allows tooltips to be stickied in the "shown" state, but that comes at the cost of left-click both toggling the sticky error message and toggling the error being hidden. One way to improve this would be right-click to toggle the error being hidden, but I don't especially like right-click because right-click is not used elsewhere in the UI.

Trying to look for some other solution; maybe a separate button to toggle the error. Since the only use case I see for toggling errors is to hide sliders, this button could be placed in the "add slider" row (like "add slider: [a] [b] [c] [all]        [hide]"), then this behavior could be toggled back on by clicking the faded error triangle again.

**Comment by jared-hughes** [comment]
Resolution:

As pointed out by @Heavenira in the discord, adding a "hide" button would increase visibility of this feature. So the "hide" button is a must-have.

Also, replace left-click to toggle error message with shift-left-click.
