### ISSUE TITLE
Folders with large lists

### ISSUE THREAD

**Issue by MathEnthusiast314** [DesModder/DesModder#289]
Implementation of permanently closed folders where I can manually set the folders I don't want to (accidentally) open and make the graph lag.
![image_2021-12-20_070634](https://user-images.githubusercontent.com/89387162/146699711-579d7092-8e9f-4e79-a57c-036bd4e04e34.png)

**Comment by jared-hughes** [comment]
The root cause of this issue is that the folder has latex expressions which are very long, causing lag in either the MathQuill backend or having too many inserted DOM nodes.

My plan to address this is plaintext mode (#197)—starting with a quick/simple implementation (maybe just removing \left, \right, and \operatorname)
