### ISSUE TITLE
Allow more greek letters recognized, like delta, etc.

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#35]
Already supported for alpha, beta, pi, tau, etc., but not all.

FabriceNeyret suggests capital Greek letters too, which would be useful (delta is δ, while Delta is the common Δ)

Related: https://chrome.google.com/webstore/detail/desmos-more-greek-letters/ehedmkmgdeekblhmnogcdimeohjilkjb

**Comment by jared-hughes** [comment]
Note that DesModder breaks the "Desmos More Greek Letters" extension (because that extension is not smart with waiting for Desmos to load), so it would be more valuable to implement this directly in DesModder.

**Comment by Mehmet41** [comment]
Old extensions like 'more greek letters' and 'desmos unlocked' no longer work due to an api issue on desmos end. These extention use to replace things such as Delta to \Delta and delta to \delta. They where very convinient to access greek letters quickly. Will this feature ever be added to DesModder?

**Comment by jared-hughes** [comment]
This feature idea remains in the state of maybe, no promises.
