### ISSUE TITLE
Desmodder not loading

### ISSUE THREAD

**Issue by Martin-exe-v2** [DesModder/DesModder#362]
Desmodder not loading on desmos
desmos link I was using: https://www.desmos.com/calculator/fwiptpooji
error logs and my guesses on what they mean
`DevTools failed to load source map: Could not load content for chrome-extension://eclmfdfimjhkmjglgdldedokjaemjfjp/index.js.map: System error: net::ERR_BLOCKED_BY_CLIENT`
"eclmfdfimjhkmjglgdldedokjaemjfjp" matches the chrome webstore download link for desmodder
`Uncaught ReferenceError: require is not defined
    at fwiptpooji:307:5`
"fwiptpooji" is the id of the desmos graph I was using
`Uncaught Error: No parser
    at q (calculator_desktop-94dae14e922dce67996c9d11483cca99b6f3dcf7.js:1:1012)
    at r (calculator_desktop-94dae14e922dce67996c9d11483cca99b6f3dcf7.js:1:2221)
    at Object.apply (script.js:2114:23)
    at script.js:2369:26
    at script.js:6981:2
    at script.js:6982:12`

**Comment by jared-hughes** [comment]
The first error just means that the source map isn't including, which is ok.

The second error is expected because part of DesModder's operation is blocking the initial load of Desmos in order to modify some stuff before Desmos loads.

The third error `Uncaught Error: No parser` is unexpected. It occurs because Desmos removed their parser module, which Desmodder depends on. I fixed this issue earlier today in 0.7.3 (https://github.com/DesModder/DesModder/releases/tag/v0.7.3), but Chrome still has to approve it. If you want to use this fixed version of DesModder now, then install it on Firefox (Firefox doesn't go through an approval process) or download the `dist-chrome.zip` on the 0.7.3 release page, and install the extension from that zip file.

To install from zip, follow these installation instructions ([based on this](https://stackoverflow.com/a/24577660/7481517)):

1. You probably want to do this in a separate Chrome profile to be safe; otherwise remove any existing DesModder install to avoid duplication
2. Download dist-chrome.zip, and unpack it to somewhere safe (not Desktop or Downloads where it might get accidentally deleted)
3. Visit chrome://extensions (via omnibox or menu -> Tools -> Extensions).
4. Enable Developer mode by ticking the checkbox in the upper-right corner.
5. Click on the "Load unpacked" button in the upper-left corner
6. Select the directory of your unpacked extension.

**Comment by jared-hughes** [comment]
This is now approved for the Chrome webstore!

If you uninstalled DesModder, you can [re-install it](https://chrome.google.com/webstore/detail/desmodder-for-desmos/eclmfdfimjhkmjglgdldedokjaemjfjp).

If you installed DesModder from zip, I suggest removing that install and installing [directly from the Chrome webstore](https://chrome.google.com/webstore/detail/desmodder-for-desmos/eclmfdfimjhkmjglgdldedokjaemjfjp) so you can get future updates automatically.

If you kept DesModder around, it may still be in 0.7.2 and buggy as before. You might want to force update to 0.7.3 by going to chrome://extensions, enabling Developer mode (in the top right), and pressing the update button (top left).

The following image from [CloudHQ](https://support.cloudhq.net/how-to-manually-update-chrome-extensions/) demonstrates how to force update:

![image](https://user-images.githubusercontent.com/20214911/172041412-e8a1dc59-97fc-4949-a564-51a88f18c3ef.png)

I'll leave this post open and pinned for a few days so people can see it.
