### ISSUE TITLE
Grahpaper disabled: no Edit Mode or Text Mode

### ISSUE THREAD

**Issue by RannyBergamotte** [DesModder/DesModder#557]
When graphpaper is disabled, there is no edit mode or text mode button. Also similar to issue #127, performance view could be automatically hidden.

**Comment by jared-hughes** [comment]
It's because they're covered up unfortunately. A good approach for fixing this would be to move the pillbox buttons next to the text mode button. This applies to the DesModder menu button mostly. The wrench menu is vanilla but could still be moved. The video creator is useless in nographpaper, and performance view is mostly useless.

**Comment by jared-hughes** [comment]
Affected by #563, but the edit mode is still disabled.

**Comment by jared-hughes** [comment]
Since only the edit mode button is covered up, this is a bug with vanilla Desmos. Can reproduce with https://desmos.com/calculator?nographpaper in incognito.
