### ISSUE TITLE
New Desmos Geometry support

### ISSUE THREAD

**Issue by RannyBergamotte** [DesModder/DesModder#561]
With the expression list and normal functions available, would be nice to have all the features of Desmodder inside the new geometry calculator.

**Comment by jared-hughes** [comment]
Thanks for bringing this up! Here's a checklist of fixes before releasing DesModder for /geometry-beta. Mostly CSS-related issues.
- [ ] Enable DesModder for /geometry-beta
- [ ] Move the pillbox buttons: they are misplaced because of the toolbar. Best option would be to put them to the left of the wrench menu, like idea'd in https://github.com/DesModder/DesModder/issues/557, but they could also just be shifted down a little
- [ ] Disable Text Mode on /geometry-beta since it is going to have a bunch of rough edges
- [ ] Pinned expressions should go above the token explorer, not below.
- [ ] Set-primary-color makes all tokens have (primary-color) border, regardless of the color of the token. This should be fixed. Need some way to merge the generated CSS with primary-color replacements from both products, or maybe choose conditionally.
- Certain objects like circle() do not work with video creator. Seems to be a bug with asyncScreenshot. I think we keep Video Creator enabled despite that.

**Comment by jared-hughes** [comment]
Added in #563
