### ISSUE TITLE
desmodder isnt letting stuff load

### ISSUE THREAD

**Issue by Fingers310** [DesModder/DesModder#602]
https://www.desmos.com/calculator/vfndz558iw
![image](https://github.com/DesModder/DesModder/assets/90801921/6b7e48d0-3f87-4d06-9e09-53a86e851e98)

**Comment by Fingers310** [comment]
its not letting stuff load for some reason
![image](https://github.com/DesModder/DesModder/assets/90801921/333a461f-5974-44cb-9963-e6a6f0804319)

**Comment by Fingers310** [comment]
Better evaluation wont fix it eather

**Comment by canisiusphysics** [comment]
With Chrome, it seems that if you disable Desmodder, restart Chrome, and then re-enable Desmodder, your graphs will show up (but without a way to edit those Desmodder features).  With Firefox, it is Desmodder enabled, see nothing (even work using no Desmodder features), or disable and see everything, but with no editing of Desmodder features.

**Comment by jared-hughes** [comment]
I've released a fix. It's now available on Firefox, and pending approval on Chrome. Follow the instuctions at [RUN_PRERELEASE.md](https://github.com/DesModder/DesModder/blob/main/docs/RUN_PRERELEASE.md) if you want it on Chrome now.

There was a deep internal error that caused the problem. I added more graceful handling, so if a similar problem arises again, it will be caught better. (It displayed Better Evaluation View because that is the first replacement that DesModder tries).

Thanks for reporting.
