### ISSUE TITLE
Intellisense suggests tokens in all of the Video Creator fields

### ISSUE THREAD

**Issue by SlimRunner** [DesModder/DesModder#639]
Autocompletion tokens are suggested in the following fields that accept only arithmetic expressions "from", "to", "step", "width", and "height".

A very minor bug since you are not supposed to type tokens there anyway, but it could confuse some users I guess.

An image just because why not :)
![image](https://github.com/DesModder/DesModder/assets/43660822/f3f4f27e-b684-4c4d-a993-26cd4842641c)

**Comment by radian628** [comment]
Hmmm, after some deliberation I think the best way of fixing this would be to somehow mark the invalid MathQuill inputs as "no-intellisense" somehow, maybe through a class or an HTML data attribute. Then I just check if the MathQuill element has the "no-intellisense" class/data attribute as an ancestor. I'll make some special exceptions for things like the settings menu, since those are built-in and I can't easily add that tag there. I'll also have a "yes-intellisense" class to override _that_, incase someone wants an intellisense-enabled input in the settings menu.

**Comment by radian628** [comment]
#640 addresses this now. Thanks for the bug report!
