### ISSUE TITLE
GLesmos crashes on unsupported hardware even when plugin is disabled

### ISSUE THREAD

**Issue by radian628** [DesModder/DesModder#690]
See this discussion for the initial bug report: https://github.com/DesModder/DesModder/discussions/689

**Comment by radian628** [comment]
To add more detail, GLesmos seems to stop graphpaper rendering if the user's browser doesn't support WebGL2 (not a complete crash as far as I can tell). The problem seems to be that `getContext("webgl2")` returns null and then you know how that goes lol.

**Comment by radian628** [comment]
This seems to occur even if the plugin is disabled, strangely.

**Comment by jared-hughes** [comment]
I can reproduce this by changing `c.getContext("webgl2"` to `c.getContext("invalid"`

**Comment by TesteTheTestCat** [comment]
i dont understand any of this

**Comment by TesteTheTestCat** [comment]
it isnt fixed
![image](https://github.com/DesModder/DesModder/assets/140556085/7304a6d7-ff48-4161-be68-7623a7998841)

**Comment by TesteTheTestCat** [comment]
or maybe my version isnt updated

**Comment by jared-hughes** [comment]
Yes, it can take a few days for the new version to roll out. I closed the issue because it's fixed on GitHub.

If you want the fix now, you can install the "nightly" version by following the instructions at https://www.desmodder.com/installation/ under "Advanced: Install from ZIP". In the "Download" subsection, don't install from Releases. Install from the nightly builds page, https://nightly.link/DesModder/DesModder/workflows/build/main.

**Comment by TesteTheTestCat** [comment]
im gonna wait, i can handle a few days without being able to graph stuff on desmos

**Comment by jared-hughes** [comment]
Desmos will still work if you disable DesModder.

**Comment by TesteTheTestCat** [comment]
okay, see you next update!

**Comment by jared-hughes** [comment]
@TesteTheTestCat update is out :)

**Comment by TesteTheTestCat** [comment]
> @TesteTheTestCat update is out :)

:3
