### ISSUE TITLE
Glesmos doesn't understand this

### ISSUE THREAD

**Issue by Apersoma** [DesModder/DesModder#944]
https://www.desmos.com/calculator/zg4xpbyfqe

**Comment by Apersoma** [comment]
I would be more specific but I don't have any more information than is provided in the graph

**Comment by jared-hughes** [comment]
This is a bug with Desmos's shader compiler. It's ticketed as a bug there, so I'm closing this here. 

The same error (`[internal] Unexpected type: Any`) appears in https://www.desmos.com/3d/d3dxqiaohq?logInternalErrors as in https://www.desmos.com/calculator/zg4xpbyfqe?logInternalErrors with GLesmos enabled.

Though note that recursion isn't supported in shaders at all. (The bug here is that the error "Sorry, I don't understand this" is unhelpful).
