### ISSUE TITLE
Add "author" to plugin settings for attribution purposes

### ISSUE THREAD

**Issue by SlimRunner** [DesModder/DesModder#95]
While I was refactoring Heavenira's script it crossed my mind that it might be beneficial to have an "author" setting in the plugin that identifies the original author(s) of the script. Given the current system, it would probably add noise to include more text in the list of toggles along with the description, but it could be useful later down the line and might also increase intentions for collaborating.

**Comment by jared-hughes** [comment]
A bit of inspiration from Atom:

![image](https://user-images.githubusercontent.com/20214911/118544493-534c5700-b70a-11eb-8400-37bd62806b5d.png)

Something like that could appear when the plugin is expanded.

Or, there could be a link to the repository when expanded, and the repository would show the primary author, though with slightly less visibility.

We could conceivably also have version number, but due to the fact that all plugins are bundled together, it doesn't really make much sense.

**Comment by jared-hughes** [comment]
Would clutter the interface. Closing for now.
