### ISSUE TITLE
Desmodder loads but makes a random blank space, attempting to clear this issue unloads desmodder.

### ISSUE THREAD

**Issue by Lobster714** [DesModder/DesModder#973]
Title, DesModder seems to be bugging out for me. Apologies for the purple shapes, my crude attempt of censoring. Also the video quality is bad since I had to compress for GitHub.

https://github.com/user-attachments/assets/9895fb76-8f67-456b-8f99-cf3031f149a3

I am using the [Thorium](https://thorium.rocks/) browser, this issue doesn't occur when I use Firefox.

**Comment by jared-hughes** [comment]
This is fixed in the latest 0.14.1 of DesModder, which is released now on Chrome and Firefox. To manually update in Chrome, either restart the browser entirely, or uninstall-reinstall the extension, or
1. Open the URL `chrome://extensions/`
2. Enable developer mode (top right)
3. Click "Update" (top left)
4. Disable developer mode (top right)

**Comment by Lobster714** [comment]
That worked, thanks
